#!/usr/bin/env python3
"""Assembles, in long format (method, domain, interaction_id, metric, value),
the per-question data for the 11 methods in table.tex, for the statistical
tests (Friedman/Nemenyi/Bonferroni/paired t-test).

Sources (found through investigation, see the conversation's report):
  - RL-Chunk (ppo, ddpg, recurrent_ppo, sac): rl_chunk/src/rl_pipeline_run/
  - BM25, Gemini: rl_chunk/src/legacy/data/
  - FAISS: rl_chunk/src/rl_pipeline/faiss_encoreweb_results/
  - ColBERT, Deep Retrieval+FAISS, Deep Retrieval+BM25: /mnt/ssd1/rafael/flow_retrieved_chunks_to_metrics/
  - Search-R1 E5: /mnt/ssd1/rafael/search-r1/

Note: the `legacy/` directory referenced below (BM25 and Gemini sources) has
since been removed from the project; those two loaders are kept for
provenance/documentation but will fail if re-run without that data.

Bug fix (confirmed with the user): Gemini and Search-R1 had their text
metrics (ROUGE-L/BLEU-4/BERTScore/Cosine) computed by comparing Gemini's
answer against ITSELF (clean_answer == clean_answer_gemini), not against the
real gold answer. Here, for these two methods, the gold answer used is the
`clean_answer` already computed in the RL-Chunk pipeline (same question,
same interaction_id) - the same gold text already used for PPO/DDPG/etc,
ensuring consistency with the rest of the comparison.

Bug fix (FAISS, confirmed with the user): the previous version used
resultados_parciais_faiss.csv, which ranked chunks by similarity to the
GOLD ANSWER (data leakage) and used all-MiniLM-L6-v2 (a different embedder
than RL-Chunk's). Replaced by faiss_encoreweb_results/, generated by
faiss_encoreweb.py: ranks by similarity to the QUERY using en_core_web_md
(the same embedder as RL-Chunk), making the "same embedder, with vs without
RL" ablation fair and leak-free.

Bug fix (Deep Retrieval, confirmed with the user): the original
3-metricas_deep_retrieval_{faiss,bm25}.parquet files came from an
extract_chunks() with a broken regex (it expected a dict format that no
longer existed at that stage), so retrieved_contexts was always [] ->
Context Precision always 0.0 and Faithfulness artificially low. There was
also a response/reference misalignment (internal reordering by
ragas.evaluate() combined with positional reattachment of metadata).
Replaced with the *_FIXED.parquet files, rebuilt from scratch from two
row-by-row verified sources (df_deep_retrieval_faiss_e_bm25.parquet for the
real chunks and 2-respostas_limpas_gemini_deep_retrieval_*.parquet for the
real LLM answers), with an explicit merge on row_id.

RAGAS does not exist for Gemini (no retrieved context - same convention as
table.tex, which marks "--" for it in those columns).
"""

import ast
import sys
from pathlib import Path

import bert_score
import numpy as np
import pandas as pd


def _parse_bracketed(x):
    """Parses strings like '[0.0]' or '[nan]' (resultados_parciais_*.csv) into a float."""
    if not isinstance(x, str) or not x.startswith("["):
        return x
    try:
        return ast.literal_eval(x)[0]
    except (ValueError, SyntaxError):
        return float(x.strip("[]"))  # covers "[nan]", which ast.literal_eval rejects

RL_PIPELINE_DIR = Path("/mnt/ssd1/rafael/rl_chunk/src/rl_pipeline")
sys.path.insert(0, str(RL_PIPELINE_DIR))
from compute_metrics import compute_bleu, compute_rouge_l, compute_cosine_similarity  # noqa: E402

LEGACY = Path("/mnt/ssd1/rafael/rl_chunk/src/legacy/data")
RL_RUN = Path("/mnt/ssd1/rafael/rl_chunk/src/rl_pipeline_run")
FLOW = Path("/mnt/ssd1/rafael/flow_retrieved_chunks_to_metrics")
SEARCHR1 = Path("/mnt/ssd1/rafael/search-r1")

TEXT_METRICS = ["ROUGE-L F1", "BLEU-4", "BERTScore F1", "Cosine Similarity"]
RAGAS_METRICS = ["faithfulness", "answer_relevancy", "answer_correctness", "context_precision", "context_recall"]
RAGAS_LABELS = {
    "faithfulness": "Faithfulness",
    "answer_relevancy": "Answer Relevancy",
    "answer_correctness": "Answer Correctness",
    "context_precision": "Context Precision",
    "context_recall": "Context Recall",
}

ALGO_LABELS = {"ppo": "PPO", "ddpg": "DDPG", "recurrent_ppo": "R-PPO", "sac": "SAC"}


def recompute_text_metrics(df: pd.DataFrame, ref_col: str, hyp_col: str) -> pd.DataFrame:
    """Recomputes ROUGE-L F1/BLEU-4/Cosine Similarity/BERTScore F1 with the SAME
    functions as rl_pipeline (compute_metrics.py), over rows with a non-empty hyp."""
    d = df[df[hyp_col].astype(str).str.strip() != ""].copy()
    d = d[d[hyp_col].notna()]
    ref = d[ref_col].astype(str).str.lower()
    hyp = d[hyp_col].astype(str).str.lower()
    d["ROUGE-L F1"] = [compute_rouge_l(r, h) for r, h in zip(ref, hyp)]
    d["BLEU-4"] = [compute_bleu(r, h) for r, h in zip(ref, hyp)]
    d["Cosine Similarity"] = [compute_cosine_similarity(r, h) for r, h in zip(ref, hyp)]
    _, _, f1 = bert_score.score(hyp.tolist(), ref.tolist(), lang="en", verbose=False)
    d["BERTScore F1"] = f1.numpy()
    return d


def melt_text(df: pd.DataFrame, method: str, id_col: str = "interaction_id") -> pd.DataFrame:
    long = df.melt(id_vars=[id_col, "domain"], value_vars=TEXT_METRICS, var_name="metric", value_name="value")
    long["method"] = method
    return long.rename(columns={id_col: "interaction_id"})[["method", "domain", "interaction_id", "metric", "value"]]


def melt_ragas(df: pd.DataFrame, method: str, id_col: str = "interaction_id") -> pd.DataFrame:
    cols = [c for c in RAGAS_METRICS if c in df.columns]
    long = df.melt(id_vars=[id_col, "domain"], value_vars=cols, var_name="metric", value_name="value")
    long["metric"] = long["metric"].map(RAGAS_LABELS)
    long["method"] = method
    return long.rename(columns={id_col: "interaction_id"})[["method", "domain", "interaction_id", "metric", "value"]]


def load_rl_chunk() -> pd.DataFrame:
    text = pd.read_parquet(RL_RUN / "3_results" / "text_metrics_per_row.parquet")
    base = pd.read_parquet(RL_RUN / "2_responses.parquet").reset_index(drop=True)
    ragas = pd.read_parquet(RL_RUN / "3_results" / "ragas_metrics_per_row.parquet").reset_index(drop=True)
    ragas["interaction_id"] = base["interaction_id"].values
    ragas["row_idx"] = base["row_idx"].values

    frames = []
    for algo, label in ALGO_LABELS.items():
        t = text[text["algo"] == algo]
        frames.append(melt_text(t, label))
        r = ragas[ragas["algo"] == algo]
        frames.append(melt_ragas(r, label))
    return pd.concat(frames, ignore_index=True)


def load_bm25() -> pd.DataFrame:
    text = pd.read_parquet(LEGACY / "rodada_artigo_bm25.parquet").rename(
        columns={"Cosine Sim": "Cosine Similarity"}
    )
    text = text[text["llm_response_bm25"].astype(str).str.strip() != ""]
    ragas = pd.read_csv(LEGACY / "resultados_parciais_bm25.csv")
    for c in RAGAS_METRICS:
        ragas[c] = ragas[c].apply(_parse_bracketed)
    return pd.concat([melt_text(text, "BM25"), melt_ragas(ragas, "BM25")], ignore_index=True)


def load_faiss() -> pd.DataFrame:
    # en_core_web_md, ranked by query (same embedder as RL-Chunk, no gold-answer
    # leakage) - see faiss_encoreweb.py and faiss_encoreweb_results/.
    idmap = _id_map()
    faiss_dir = RL_PIPELINE_DIR / "faiss_encoreweb_results"

    text = pd.read_parquet(faiss_dir / "text_metrics_per_row.parquet")
    text = text.merge(idmap, on=["domain", "query"], how="inner")
    text = text[["interaction_id", "domain"] + TEXT_METRICS]

    ragas = pd.read_parquet(faiss_dir / "ragas_metrics_per_row.parquet").rename(columns={"user_input": "query"})
    ragas = ragas.merge(idmap, on=["domain", "query"], how="inner")
    return pd.concat([melt_text(text, "FAISS"), melt_ragas(ragas, "FAISS")], ignore_index=True)


def _id_map() -> pd.DataFrame:
    """(domain, query) -> interaction_id, from the RL-Chunk dataset (covers all 250 questions)."""
    base = pd.read_parquet(RL_RUN / "2_responses.parquet")
    return base[["domain", "query", "interaction_id"]].drop_duplicates(subset=["domain", "query"])


def load_colbert_style(step2_path: Path, step3_path: Path, method: str) -> pd.DataFrame:
    idmap = _id_map()
    base = pd.read_parquet(step2_path).merge(idmap, on=["domain", "query"], how="inner")
    text = recompute_text_metrics(base, "clean_answer", "llm_response_clean")
    text = text[["interaction_id", "domain"] + TEXT_METRICS]

    ragas = pd.read_parquet(step3_path).rename(columns={"user_input": "query"})
    ragas = ragas.merge(idmap, on=["domain", "query"], how="inner")
    return pd.concat([melt_text(text, method), melt_ragas(ragas, method)], ignore_index=True)


def load_searchr1() -> pd.DataFrame:
    gold = pd.read_parquet(RL_RUN / "2_responses.parquet")[["interaction_id", "clean_answer"]].drop_duplicates(
        subset="interaction_id"
    )
    base = pd.read_parquet(SEARCHR1 / "sampled_50_with_selected_chunks_com_response_searchr1_gemini.parquet")
    base = base.drop(columns=["clean_answer"]).merge(gold, on="interaction_id", how="inner")  # correct gold answer
    text = recompute_text_metrics(base, "clean_answer", "llm_response_searchr1")
    text = text[["interaction_id", "domain"] + TEXT_METRICS]

    idmap = _id_map()
    ragas = pd.read_parquet(SEARCHR1 / "searchr1_gemini_ragas_metrics_merged.parquet").rename(
        columns={"user_input": "query"}
    )
    ragas = ragas.merge(idmap, on=["domain", "query"], how="inner")
    return pd.concat([melt_text(text, "Search-R1 E5"), melt_ragas(ragas, "Search-R1 E5")], ignore_index=True)


def load_gemini() -> pd.DataFrame:
    gold = pd.read_parquet(RL_RUN / "2_responses.parquet")[["interaction_id", "clean_answer"]].drop_duplicates(
        subset="interaction_id"
    )
    base = pd.read_parquet(LEGACY / "sampled_50_per_domain_gemini_answ_response_clean.parquet")
    base = base.drop(columns=["clean_answer"]).merge(gold, on="interaction_id", how="inner")  # correct gold answer
    text = recompute_text_metrics(base, "clean_answer", "answers_llm_gemini")
    text = text[["interaction_id", "domain"] + TEXT_METRICS]
    return melt_text(text, "Gemini")  # no RAGAS - same convention as table.tex


def main():
    print("Loading RL-Chunk (PPO/DDPG/R-PPO/SAC)...")
    rl_chunk = load_rl_chunk()
    print("Loading BM25...")
    bm25 = load_bm25()
    print("Loading FAISS (recomputing text metrics)...")
    faiss = load_faiss()
    print("Loading ColBERT (recomputing text metrics)...")
    colbert = load_colbert_style(
        FLOW / "2-respostas_limpas_gemini_colbert.parquet", FLOW / "3-metricas_colbert.parquet", "ColBERT"
    )
    print("Loading Deep Retrieval + FAISS (recomputing text metrics, fixed RAGAS)...")
    dr_faiss = load_colbert_style(
        FLOW / "2-respostas_limpas_gemini_deep_retrieval_faiss.parquet",
        FLOW / "3-metricas_deep_retrieval_faiss_FIXED.parquet",
        "Deep Retrieval+FAISS",
    )
    print("Loading Deep Retrieval + BM25 (recomputing text metrics, fixed RAGAS)...")
    dr_bm25 = load_colbert_style(
        FLOW / "2-respostas_limpas_gemini_deep_retrieval_bm25.parquet",
        FLOW / "3-metricas_deep_retrieval_bm25_FIXED.parquet",
        "Deep Retrieval+BM25",
    )
    print("Loading Search-R1 E5 (recomputing text metrics with the correct gold answer)...")
    searchr1 = load_searchr1()
    print("Loading Gemini (recomputing text metrics with the correct gold answer)...")
    gemini = load_gemini()

    long_df = pd.concat(
        [rl_chunk, bm25, faiss, colbert, dr_faiss, dr_bm25, searchr1, gemini], ignore_index=True
    )
    long_df = long_df.dropna(subset=["value"])
    out_path = Path(__file__).parent / "output" / "long_format_all_methods.parquet"
    long_df.to_parquet(out_path)
    print(f"\nSaved to {out_path} ({len(long_df)} rows)")
    print(long_df.groupby(["method", "metric"]).size().unstack("metric"))


if __name__ == "__main__":
    main()
