#!/usr/bin/env python3
"""Generates the LLM answer from the chunks selected by the RL agent, cleans
that answer (flags it as empty when the LLM didn't actually answer), and
cleans the gold-standard answer (clean_answer) for a fair comparison in the
text metrics.

Usage:
    python generate_responses.py --input inference.parquet --output responses.parquet
"""

import argparse
import concurrent.futures as cf
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import pandas as pd
from tqdm import tqdm

from llm import clean_gold_answer, clean_response, get_response_from_llm


def parallel_map(fn, items, workers, desc):
    results = [None] * len(items)
    with cf.ThreadPoolExecutor(max_workers=workers) as ex:
        futures = {ex.submit(fn, *args): i for i, args in enumerate(items)}
        for fut in tqdm(cf.as_completed(futures), total=len(futures), desc=desc):
            results[futures[fut]] = fut.result()
    return results


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, help="parquet generated by infer.py")
    parser.add_argument("--output", required=True)
    parser.add_argument("--workers", type=int, default=8, help="parallel OpenAI calls")
    parser.add_argument("--limit", type=int, default=None, help="for quick testing: use only the first N rows")
    args = parser.parse_args()

    df = pd.read_parquet(args.input).reset_index(drop=True)
    if args.limit:
        df = df.head(args.limit).reset_index(drop=True)

    # clean_answer (gold) is computed once per unique dataset row (row_idx),
    # not once per (row, algorithm) - the gold answer doesn't depend on the algorithm.
    unique_rows = df.drop_duplicates(subset="row_idx")[["row_idx", "query", "answer"]]
    print(f"Cleaning {len(unique_rows)} gold-standard answers...")
    cleaned_gold = parallel_map(
        clean_gold_answer,
        list(zip(unique_rows["query"], unique_rows["answer"])),
        args.workers, "clean_answer",
    )
    gold_map = dict(zip(unique_rows["row_idx"], cleaned_gold))
    df["clean_answer"] = df["row_idx"].map(gold_map)

    print(f"Generating LLM answers for {len(df)} rows (row x algorithm)...")
    responses = parallel_map(
        get_response_from_llm,
        list(zip(df["query"], df["chunks_selected"])),
        args.workers, "llm_response",
    )
    df["llm_response_raw"], df["input_tokens"], df["output_tokens"] = zip(*responses)

    print("Cleaning LLM answers (removing refusals/non-answers)...")
    df["llm_response"] = parallel_map(
        clean_response, [(r,) for r in df["llm_response_raw"]], args.workers, "clean_response",
    )

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(args.output)
    n_answered = (df["llm_response"].astype(str).str.strip() != "").sum()
    print(f"\nSaved to {args.output} ({len(df)} rows, {n_answered} with a non-empty answer)")


if __name__ == "__main__":
    main()
