#!/usr/bin/env bash
# Full evaluation pipeline: inference (RL agent picks the chunks) -> LLM
# answer generation -> cleaning -> metrics (ROUGE-L F1, BLEU-4, BERTScore F1,
# Cosine Similarity, Faithfulness, Answer Relevancy, Answer Correctness,
# Context Precision, Context Recall, mean_chunks_selected) -> final
# domain x algorithm table.
#
# Usage:
#   ./infer.sh path/to/dataset.parquet [model_dir] [run_dir]
#
# The dataset needs the columns: domain, query, answer, page_results_text
# (and interaction_id/question_type/static_or_dynamic if available).
# model_dir should be the folder generated by train.sh (default: rl_pipeline_models/).
#
# Optional environment variables:
#   ALGORITHMS   comma-separated list (default: ppo,ddpg,recurrent_ppo,sac)
#   WORKERS      parallel OpenAI calls during answer generation/cleaning (default: 8)
#   LIMIT        for quick testing: use only the first N inference rows

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PIPELINE_DIR="$SCRIPT_DIR/rl_pipeline"

DATASET="${1:?Usage: ./infer.sh path/to/dataset.parquet [model_dir] [run_dir]}"
MODEL_DIR="${2:-$SCRIPT_DIR/rl_pipeline_models}"
RUN_DIR="${3:-$SCRIPT_DIR/rl_pipeline_run}"

ALGORITHMS="${ALGORITHMS:-ppo,ddpg,recurrent_ppo,sac}"
WORKERS="${WORKERS:-8}"

mkdir -p "$RUN_DIR"

INFER_OUT="$RUN_DIR/1_inference.parquet"
RESPONSES_OUT="$RUN_DIR/2_responses.parquet"
RESULTS_DIR="$RUN_DIR/3_results"

LIMIT_ARGS=()
[[ -n "${LIMIT:-}" ]] && LIMIT_ARGS+=(--limit "$LIMIT")

cd "$PIPELINE_DIR"

echo "== [1/3] Inference (chunk selection by the RL agent) =="
python3 -u infer.py \
    --dataset "$DATASET" \
    --model-dir "$MODEL_DIR" \
    --output "$INFER_OUT" \
    --algorithms "$ALGORITHMS"

echo
echo "== [2/3] LLM answer generation and cleaning =="
python3 -u generate_responses.py \
    --input "$INFER_OUT" \
    --output "$RESPONSES_OUT" \
    --workers "$WORKERS" \
    "${LIMIT_ARGS[@]}"

echo
echo "== [3/3] Metrics (ROUGE-L F1, BLEU-4, BERTScore F1, Cosine Similarity, RAGAS, mean_chunks_selected) =="
python3 -u compute_metrics.py \
    --input "$RESPONSES_OUT" \
    --output-dir "$RESULTS_DIR"

echo
echo "Results at: $RESULTS_DIR/final_rl_proposal_table.csv (and .xlsx)"
echo "Inference sustainability/latency (mean/std + CodeCarbon): $RUN_DIR/sustainability_inference.csv"
